services:
  redis:
    image: redis

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "${PG_DB_DBNAME}"
      POSTGRES_USER: "${PG_DB_USER}"
      POSTGRES_PASSWORD: "${PG_DB_PWD}"
      PGPORT: "${PG_DB_PORT}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - adbot-data:/var/lib/postgresql/data

  adbot:
    image: adbot

volumes:
  adbot-data: