"""user model

Revision ID: b8ffdff62dfe
Revises: cf4378657cbc
Create Date: 2023-12-15 11:53:43.921577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = 'b8ffdff62dfe'
down_revision: Union[str, None] = 'cf4378657cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('telegram_id', sa.Integer(), nullable=True),
        sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('lang', sa.Enum('en', 'ru', name='lang'), nullable=False),
        sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
