"""user-publication-link model

Revision ID: 29a06242f9db
Revises: 01648d2c63ef
Create Date: 2023-12-26 11:08:56.108374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '29a06242f9db'
down_revision: Union[str, None] = '01648d2c63ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users_publications_links',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_uuid', sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column('publication_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
        sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_uuid', 'publication_id', name='u_user_pub')
    )
    op.create_index(op.f('ix_users_publications_links_id'), 'users_publications_links', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_publications_links_id'), table_name='users_publications_links')
    op.drop_table('users_publications_links')
    # ### end Alembic commands ###
