"""user-keyword link

Revision ID: 192abfd31097
Revises: f9210507a6fc
Create Date: 2023-12-18 16:19:47.917616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '192abfd31097'
down_revision: Union[str, None] = 'f9210507a6fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users_keywords_links',
        sa.Column('user_uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column('keyword_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
        sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
        sa.PrimaryKeyConstraint('user_uuid', 'keyword_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_keywords_links')
    # ### end Alembic commands ###
